# Site settings
title: Your awesome title
email: 670116586@qq.com #your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/my-awesome-site" # the subpath of your site, e.g. /blog/
url: "" #http://yourdomain.com" # the base hostname & protocol for your site\baseurl
host: "127.0.0.1"
port: "8080"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
